export const webTableBtn = () => cy.get("#item-3");
export const addNewRecordBtn = () => cy.get("#addNewRecordButton");
export const firstNameInput = () => cy.get("#firstName");
export const lastNameInput = () => cy.get("#lastName");
export const userEmailInput = () => cy.get("#userEmail");
export const ageInput = () => cy.get("#age");
export const salaryInput = () => cy.get("#salary");
export const departmentInput = () => cy.get("#department");
export const submitBtn = () => cy.get("#submit");
